name: Check links

on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --accept 200,429 README.md
          fail: true
